### PR TITLE
Use new base url for thunderstore client

### PR DESCRIPTION
**Pull request by xaviablaza**
## Description
Update base url for thunderstore client

### CODE REVIEW

**Comment by xaviablaza** [comment]
@Weltinio Can we re-run the test and make sure this works?

**Comment by Weltinio** [comment]
@xaviablaza reran the tests and it failed. Specs are failing need to probably fix specs

**Comment by xaviablaza** [comment]
Yes, I am suggesting that you fix the specs

**Review by Weltinio — APPROVED** [review]
Specs are passing now.

**Pull request merged**
